$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
    responsive:{
        0:{
            items:1
        },
        400: {
            items:1.5
        },
        500:{
            items:2.5
        },
        730:{
            items:3.5
        },
        950:{
            items:4.5
        },
        1050:{
            items:5.5
        },
        1200:{
            items:6.5
        }
    }
})